### ISSUE TITLE
Many Elements show up above mobile sticky header

### ISSUE THREAD

**Issue by jasonnance** [FHWA/RDE-Visualization-Website#22]
Since the legend has to show up over the leaflet map, I think we probably need to just raise the z-index on the mobile header.

**Comment by wengerm50** [comment]
- Loading Div (Element 1/2/3)
- Element 2 leaflet controls
- Element 3 leaflet controls
- Element 5 leaflet controls
- Element 5 Reset Dashboard Sticky header (if page loaded with mobile header)... (which leads to other questions about how changing the screen size affects the functionality of this sticky dashboard header)
