### ISSUE TITLE
Brake and exterior light values aren't merged properly on element 6

### ISSUE THREAD

**Issue by clayheaton** [FHWA/RDE-Visualization-Website#25]
![screen shot 2016-08-30 at 3 08 18 pm](https://cloud.githubusercontent.com/assets/205364/18103204/9af59272-6ec3-11e6-9d97-84848e7df7f0.png)

![screen shot 2016-08-30 at 3 08 04 pm](https://cloud.githubusercontent.com/assets/205364/18103211/9d7510a4-6ec3-11e6-8843-6ea40510f509.png)

**Comment by wengerm50** [comment]
Marcia and I investigated this some today.  It appears that the version of d3_v3 being used on her branch and the version that Jason switch to when cleaning up the dependencies MIGHT different.  @jasonnance Do you remember if you just moved her d3_v3.min.js to the overall js folder structure or was there already one there?

As for Exterior Lights it appears that somewhere along the line Marcia made a change that introduced a bug.  The bug did not break the visual and we did not notice until this issue.  She is working on a fix now.

**Comment by jasonnance** [comment]
Ack, yeah, I didn't want to be using 3 different versions of d3 if possible, so I used the version of d3_v3 (3.5.17) that was already there instead of the one in Marcia's branch (3.4.11).  Didn't see any errors, so I figured it was OK.  I'll add it and switch element 6 to it.  Sorry about that.
